# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Data\_PROGETTI\APPS\PRJ_MANAGER_2021\windows\pages\comp_page\comp_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompPage(object):
    def setupUi(self, CompPage):
        CompPage.setObjectName("CompPage")
        CompPage.resize(873, 604)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CompPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiCompView = QtWidgets.QTreeView(CompPage)
        self.uiCompView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.uiCompView.setIndentation(20)
        self.uiCompView.setAnimated(True)
        self.uiCompView.setObjectName("uiCompView")
        self.horizontalLayout.addWidget(self.uiCompView)

        self.retranslateUi(CompPage)
        QtCore.QMetaObject.connectSlotsByName(CompPage)

    def retranslateUi(self, CompPage):
        _translate = QtCore.QCoreApplication.translate
        CompPage.setWindowTitle(_translate("CompPage", "Form"))
