# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\popup_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_editor(object):
    def setupUi(self, popup_editor):
        popup_editor.setObjectName("popup_editor")
        popup_editor.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(popup_editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiLEName = QtWidgets.QLineEdit(popup_editor)
        self.uiLEName.setObjectName("uiLEName")
        self.verticalLayout.addWidget(self.uiLEName)
        self.uiTEDesc = QtWidgets.QTextEdit(popup_editor)
        self.uiTEDesc.setObjectName("uiTEDesc")
        self.verticalLayout.addWidget(self.uiTEDesc)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiBtnOk = QtWidgets.QPushButton(popup_editor)
        self.uiBtnOk.setObjectName("uiBtnOk")
        self.horizontalLayout.addWidget(self.uiBtnOk)
        self.uiBtnCancel = QtWidgets.QPushButton(popup_editor)
        self.uiBtnCancel.setObjectName("uiBtnCancel")
        self.horizontalLayout.addWidget(self.uiBtnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(popup_editor)
        QtCore.QMetaObject.connectSlotsByName(popup_editor)

    def retranslateUi(self, popup_editor):
        _translate = QtCore.QCoreApplication.translate
        popup_editor.setWindowTitle(_translate("popup_editor", "Form"))
        self.uiBtnOk.setText(_translate("popup_editor", "Ok"))
        self.uiBtnCancel.setText(_translate("popup_editor", "Cancel"))
