# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiCompView = QtWidgets.QTreeView(self.centralwidget)
        self.uiCompView.setObjectName("uiCompView")
        self.horizontalLayout.addWidget(self.uiCompView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.uiMenu = QtWidgets.QMenuBar(MainWindow)
        self.uiMenu.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.uiMenu.setObjectName("uiMenu")
        self.uiMenuFile = QtWidgets.QMenu(self.uiMenu)
        self.uiMenuFile.setObjectName("uiMenuFile")
        self.uiMenuEdit = QtWidgets.QMenu(self.uiMenu)
        self.uiMenuEdit.setObjectName("uiMenuEdit")
        self.uiMenuView = QtWidgets.QMenu(self.uiMenu)
        self.uiMenuView.setObjectName("uiMenuView")
        self.uiMenuSettings = QtWidgets.QMenu(self.uiMenu)
        self.uiMenuSettings.setObjectName("uiMenuSettings")
        MainWindow.setMenuBar(self.uiMenu)
        self.uiActNew = QtWidgets.QAction(MainWindow)
        self.uiActNew.setObjectName("uiActNew")
        self.uiActOpen = QtWidgets.QAction(MainWindow)
        self.uiActOpen.setObjectName("uiActOpen")
        self.uiActSave = QtWidgets.QAction(MainWindow)
        self.uiActSave.setObjectName("uiActSave")
        self.uiActSave_As = QtWidgets.QAction(MainWindow)
        self.uiActSave_As.setObjectName("uiActSave_As")
        self.uiActAddNode = QtWidgets.QAction(MainWindow)
        self.uiActAddNode.setObjectName("uiActAddNode")
        self.uiActRemoveNode = QtWidgets.QAction(MainWindow)
        self.uiActRemoveNode.setObjectName("uiActRemoveNode")
        self.uiActExpand = QtWidgets.QAction(MainWindow)
        self.uiActExpand.setObjectName("uiActExpand")
        self.uiActCollapse = QtWidgets.QAction(MainWindow)
        self.uiActCollapse.setObjectName("uiActCollapse")
        self.uiActOpenSettingsWindow = QtWidgets.QAction(MainWindow)
        self.uiActOpenSettingsWindow.setObjectName("uiActOpenSettingsWindow")
        self.uiMenuFile.addAction(self.uiActNew)
        self.uiMenuFile.addAction(self.uiActOpen)
        self.uiMenuFile.addAction(self.uiActSave)
        self.uiMenuFile.addAction(self.uiActSave_As)
        self.uiMenuEdit.addAction(self.uiActAddNode)
        self.uiMenuEdit.addAction(self.uiActRemoveNode)
        self.uiMenuView.addAction(self.uiActExpand)
        self.uiMenuView.addAction(self.uiActCollapse)
        self.uiMenuSettings.addAction(self.uiActOpenSettingsWindow)
        self.uiMenu.addAction(self.uiMenuFile.menuAction())
        self.uiMenu.addAction(self.uiMenuEdit.menuAction())
        self.uiMenu.addAction(self.uiMenuView.menuAction())
        self.uiMenu.addAction(self.uiMenuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uiMenuFile.setTitle(_translate("MainWindow", "File"))
        self.uiMenuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.uiMenuView.setTitle(_translate("MainWindow", "View"))
        self.uiMenuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.uiActNew.setText(_translate("MainWindow", "New"))
        self.uiActOpen.setText(_translate("MainWindow", "Open"))
        self.uiActSave.setText(_translate("MainWindow", "Save"))
        self.uiActSave_As.setText(_translate("MainWindow", "Save As"))
        self.uiActAddNode.setText(_translate("MainWindow", "Add Node"))
        self.uiActRemoveNode.setText(_translate("MainWindow", "Remove Node"))
        self.uiActExpand.setText(_translate("MainWindow", "Expand"))
        self.uiActCollapse.setText(_translate("MainWindow", "Collapse"))
        self.uiActOpenSettingsWindow.setText(_translate("MainWindow", "Open Settings Window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
