# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Data\_PROGETTI\APPS\PRJ_MANAGER_2021\windows\widgets\switchable_combobox\switchable_combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SwitchableCombobox(object):
    def setupUi(self, SwitchableCombobox):
        SwitchableCombobox.setObjectName("SwitchableCombobox")
        SwitchableCombobox.resize(260, 82)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SwitchableCombobox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stacked_widget = QtWidgets.QStackedWidget(SwitchableCombobox)
        self.stacked_widget.setObjectName("stacked_widget")
        self.line_edit_frame = QtWidgets.QWidget()
        self.line_edit_frame.setObjectName("line_edit_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.line_edit_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit = QtWidgets.QLineEdit(self.line_edit_frame)
        self.line_edit.setReadOnly(True)
        self.line_edit.setObjectName("line_edit")
        self.horizontalLayout_2.addWidget(self.line_edit)
        self.stacked_widget.addWidget(self.line_edit_frame)
        self.combobox_frame = QtWidgets.QWidget()
        self.combobox_frame.setObjectName("combobox_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.combobox_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.combobox_frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.stacked_widget.addWidget(self.combobox_frame)
        self.horizontalLayout.addWidget(self.stacked_widget)

        self.retranslateUi(SwitchableCombobox)
        QtCore.QMetaObject.connectSlotsByName(SwitchableCombobox)

    def retranslateUi(self, SwitchableCombobox):
        _translate = QtCore.QCoreApplication.translate
        SwitchableCombobox.setWindowTitle(_translate("SwitchableCombobox", "Form"))
